In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=sns.load_dataset("iris")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [5]:
df = df[df["species"] != "virginica"]

In [6]:
df["species"]=df["species"].map({"versicolor":1, "setosa":0})

C:\Users\Himanshi Madan\AppData\Local\Temp\ipykernel_15448\724762083.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["species"]=df["species"].map({"versicolor":1, "setosa":0})

In [7]:
df

    sepal_length  sepal_width  petal_length  petal_width  species
0            5.1          3.5           1.4          0.2        0
1            4.9          3.0           1.4          0.2        0
2            4.7          3.2           1.3          0.2        0
3            4.6          3.1           1.5          0.2        0
4            5.0          3.6           1.4          0.2        0
..           ...          ...           ...          ...      ...
95           5.7          3.0           4.2          1.2        1
96           5.7          2.9           4.2          1.3        1
97           6.2          2.9           4.3          1.3        1
98           5.1          2.5           3.0          1.1        1
99           5.7          2.8           4.1          1.3        1

[100 rows x 5 columns]

In [8]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [9]:
X

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
..           ...          ...           ...          ...
95           5.7          3.0           4.2          1.2
96           5.7          2.9           4.2          1.3
97           6.2          2.9           4.3          1.3
98           5.1          2.5           3.0          1.1
99           5.7          2.8           4.1          1.3

[100 rows x 4 columns]

In [10]:
Y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: species, Length: 100, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.25, random_state=42)

In [13]:
X_train

    sepal_length  sepal_width  petal_length  petal_width
15           5.7          4.4           1.5          0.4
40           5.0          3.5           1.3          0.3
96           5.7          2.9           4.2          1.3
9            4.9          3.1           1.5          0.1
72           6.3          2.5           4.9          1.5
..           ...          ...           ...          ...
60           5.0          2.0           3.5          1.0
71           6.1          2.8           4.0          1.3
14           5.8          4.0           1.2          0.2
92           5.8          2.6           4.0          1.2
51           6.4          3.2           4.5          1.5

[75 rows x 4 columns]

In [14]:
X_test

    sepal_length  sepal_width  petal_length  petal_width
83           6.0          2.7           5.1          1.6
53           5.5          2.3           4.0          1.3
70           5.9          3.2           4.8          1.8
45           4.8          3.0           1.4          0.3
44           5.1          3.8           1.9          0.4
39           5.1          3.4           1.5          0.2
22           4.6          3.6           1.0          0.2
80           5.5          2.4           3.8          1.1
10           5.4          3.7           1.5          0.2
0            5.1          3.5           1.4          0.2
18           5.7          3.8           1.7          0.3
30           4.8          3.1           1.6          0.2
73           6.1          2.8           4.7          1.2
33           5.5          4.2           1.4          0.2
90           5.5          2.6           4.4          1.2
4            5.0          3.6           1.4          0.2
76           6.8          2.8           4.8          1.4
77           6.7          3.0           5.0          1.7
12           4.8          3.0           1.4          0.1
31           5.4          3.4           1.5          0.4
55           5.7          2.8           4.5          1.3
88           5.6          3.0           4.1          1.3
26           5.0          3.4           1.6          0.4
42           4.4          3.2           1.3          0.2
69           5.6          2.5           3.9          1.1

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
classifier = LogisticRegression()

In [17]:
classifier.fit(X_train, Y_train)

LogisticRegression()

In [18]:
Y_pred = classifier.predict(X_test)

In [19]:
Y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1], dtype=int64)

In [20]:
np.array(Y_test)

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1], dtype=int64)

In [21]:
from sklearn.metrics import accuracy_score, classification_report
score = accuracy_score(Y_test, Y_pred)
score

1.0

In [22]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        11

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25